helmCharts:
  - name: argocd-image-updater
    repo: https://argoproj.github.io/argo-helm
    version: 0.12.2
    releaseName: argocd-image-updater
    namespace: argocd
    valuesFile: values.yaml
    includeCRDs: true
